"""Configuração centralizada do ACTA AI.

Este módulo é o único ponto da aplicação que carrega `.env` e lê variáveis de
ambiente. Módulos de runtime devem importar constantes ou helpers daqui.
"""

from __future__ import annotations

import os

from dotenv import load_dotenv

load_dotenv()


NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

ACTA_GROQ_PRIMARY_MODEL = "openai/gpt-oss-120b"
ACTA_GROQ_FAST_MODEL = "openai/gpt-oss-20b"
ACTA_GROQ_TIMEOUT_SECONDS = 8
ACTA_GROQ_MAX_RETRIES = 0
ACTA_GROQ_REASONING_EFFORT = "low"

ACTA_LLM_PRIMARY_MODEL = "nvidia/nemotron-3-super-120b-a12b"
ACTA_LLM_PRIMARY_FALLBACK_MODEL = "nvidia/nemotron-3-super-120b-a12b"
ACTA_LLM_FAST_MODEL = "nvidia/nemotron-3-super-120b-a12b"
ACTA_LLM_FAST_FALLBACK_MODEL = "nvidia/nemotron-3-super-120b-a12b"
ACTA_LLM_PRIMARY_MAX_TOKENS = 768
ACTA_LLM_FAST_MAX_TOKENS = 384
ACTA_LLM_FAST_REASONING_BUDGET = 0

ACTA_MCP_DEFAULT_URL = "http://127.0.0.1:8000/mcp"
ACTA_MCP_DEFAULT_TIMEOUT_SECONDS = 20.0
ACTA_MCP_DEFAULT_MAX_ATTEMPTS = 2

ACTA_MCP_URL = os.getenv("ACTA_MCP_URL", ACTA_MCP_DEFAULT_URL)
ACTA_MCP_API_KEY = os.getenv("ACTA_MCP_API_KEY")
ACTA_MCP_TIMEOUT_SECONDS = float(
    os.getenv("ACTA_MCP_TIMEOUT_SECONDS", str(ACTA_MCP_DEFAULT_TIMEOUT_SECONDS))
)
ACTA_MCP_MAX_ATTEMPTS = max(
    1, int(os.getenv("ACTA_MCP_MAX_ATTEMPTS", str(ACTA_MCP_DEFAULT_MAX_ATTEMPTS)))
)
ACTA_MCP_USUARIO_ID = int(os.getenv("ACTA_MCP_USUARIO_ID", "0"))
ACTA_MCP_EMPRESA_ID = int(os.getenv("ACTA_MCP_EMPRESA_ID", "0"))

MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://127.0.0.1:27018")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME", os.getenv("MONGODB_DATABASE", "acta_ai"))
ACTA_SYSTEM_FEATURES_DB_NAME = os.getenv("ACTA_SYSTEM_FEATURES_DB_NAME", "acta")
QDRANT_CLUSTER_ENDPOINT = os.getenv("QDRANT_CLUSTER_ENDPOINT")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_MEMORY_MESSAGES_COLLECTION_NAME = os.getenv(
    "QDRANT_MEMORY_MESSAGES_COLLECTION_NAME", "memoria_mensagens"
)
QDRANT_MEMORY_COLLECTION_NAME = os.getenv("QDRANT_MEMORY_COLLECTION_NAME", "memoria_usuario")
QDRANT_MEMORY_VECTOR_SIZE = int(os.getenv("QDRANT_MEMORY_VECTOR_SIZE", "768"))
QDRANT_TIMEOUT_SECONDS = float(os.getenv("QDRANT_TIMEOUT_SECONDS", "10"))
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
ACTA_MEMORY_MESSAGE_RETENTION_DAYS = int(os.getenv("ACTA_MEMORY_MESSAGE_RETENTION_DAYS", "90"))
ACTA_MEMORY_INFERRED_RETENTION_DAYS = int(os.getenv("ACTA_MEMORY_INFERRED_RETENTION_DAYS", "180"))
ACTA_MEMORY_RECENT_MESSAGES = int(os.getenv("ACTA_MEMORY_RECENT_MESSAGES", "8"))
ACTA_MEMORY_SUMMARY_EVERY_MESSAGES = int(os.getenv("ACTA_MEMORY_SUMMARY_EVERY_MESSAGES", "12"))

ACTA_ENFORCE_SPECIALIST_TOOL = True # Força o especialista a usar uma tool.
ACTA_JUDGE_LLM = True # Força o uso de um llm pra julgamento de resposta. Para testes, prefira usar False.
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_TRACES_ENDPOINT")
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_METRICS_ENDPOINT")
OTEL_EXPORTER_OTLP_TRACES_HEADERS = os.getenv("OTEL_EXPORTER_OTLP_TRACES_HEADERS")
OTEL_EXPORTER_OTLP_METRICS_HEADERS = os.getenv("OTEL_EXPORTER_OTLP_METRICS_HEADERS")
